# Generated by Django 4.2.15 on 2024-08-08 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foods', '0002_food_food_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='food_type',
            field=models.SlugField(choices=[('MEAT', 'Meat'), ('FRUIT', 'Fruit'), ('VEGETABLE', 'Vegetable'), ('GRAINS', 'Grains'), ('MILK', 'Milk'), ('EGGS', 'Eggs'), ('FATS', 'Fats'), ('SUGAR', 'Sugar'), ('BEVERAGES', 'Beverages')], default='MEAT', max_length=10),
        ),
    ]
