# Generated by Django 4.2.15 on 2024-08-08 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foods', '0005_alter_food_food_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='slug',
            field=models.SlugField(default=models.CharField(max_length=20)),
        ),
    ]
