# Generated by Django 4.2.15 on 2024-08-08 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foods', '0007_alter_food_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='food_type',
            field=models.SlugField(choices=[('MEAT', 'Meat'), ('FRUIT', 'Fruit'), ('VEGETABLE', 'Vegetable'), ('GRAINS', 'Grains'), ('DAIRY', 'Dairy'), ('FATS', 'Fats'), ('SUGAR', 'Sugar'), ('BEVERAGES', 'Beverages')], default='MEAT'),
        ),
    ]
